/**
 * ESA OS — Energy Domain / Credits / Allocation
 * Alertas e limiares da camada de rateio e saldo.
 */

export const ALLOCATION_ALERT_CODE = Object.freeze({
  HIGH_BENEFICIARY_CREDIT_BALANCE:       'HIGH_BENEFICIARY_CREDIT_BALANCE',
  LOW_BENEFICIARY_CREDIT_BALANCE:        'LOW_BENEFICIARY_CREDIT_BALANCE',
  ALLOCATION_PERCENTAGE_TOTAL_INVALID:   'ALLOCATION_PERCENTAGE_TOTAL_INVALID',
  PARTIAL_MANUAL_ALLOCATION_NOT_ALLOWED: 'PARTIAL_MANUAL_ALLOCATION_NOT_ALLOWED',
  CONSUMPTION_ABOVE_AVERAGE:             'CONSUMPTION_ABOVE_AVERAGE',
  NEGATIVE_BALANCE:                      'NEGATIVE_BALANCE',
  MAX_PREVENTIVE_MARGIN_EXCEEDED:        'MAX_PREVENTIVE_MARGIN_EXCEEDED',
});

/**
 * Limiares operacionais default.
 * Todos os valores são configuráveis via options.thresholds nas calculadoras.
 */
export const ALLOCATION_THRESHOLDS = Object.freeze({
  HIGH_BALANCE_COVERAGE_MONTHS:     1.5,
  CONSUMPTION_ABOVE_AVERAGE_FACTOR: 1.10,
  MAX_PREVENTIVE_MARGIN_PCT:        20,
  MANUAL_ALLOCATION_TOLERANCE_PP:   0.01,
});
